### ISSUE TITLE
Legend squished when changing to .png format

### ISSUE THREAD

**Issue by ytakemon** [joiningdata/lollipops#47]
Hello,

I am running the following code to generate a .png file of my protein of interest. I was wondering if there was a way to reformat the legend so that they are not overlapping and display clearly. I have been adjusting the width `-w` option, but I couldn't resolve my problem. 

Do you have any recommendations for how I can adjust the height so that the legends aren't overlapping?

```
./lollipops \
-o=ACH000840_CIC_long_lollipop.png \
-w=2500 -dpi=500 \
-legend -labels -U I3L2J0 S1703*@100
```

Interestingly this problem doesn't occur when I use the .svg format:
```
./lollipops \
-o=ACH000840_CIC_long_lollipop.svg \
-legend -labels -U I3L2J0 S1703*@100
```

Thank you in advance!

**Comment by pbnjay** [comment]
interesting, it looks like the DPI setting isn't taken into account with the font sizes. I should be able to get a fix in soon

**Comment by pbnjay** [comment]
OK can you try the latest release and let me know if it works?
https://github.com/joiningdata/lollipops/releases/tag/v1.5.3

**Comment by ytakemon** [comment]
Hi @pbnjay - works well on my end! Thanks for the quick fix!
