### ISSUE TITLE
Lollipop usage

### ISSUE THREAD

**Issue by coolmak32** [joiningdata/lollipops#51]
Hello! 
I am not familiar with Go language. I am trying to plot some mutations for mice in a lollipop diagram. I downloaded the zip file for my OS. Unzipped it and ran the .exe file (opened in cmd). I see all the options and everything but now what? Cmd does not let me enter any command (as "enter" is coded to exit). What command line is exactly used to run this software? There is nothing given in the usage part of this poorly written software description. Nothing has mentioned the publication either.

Can somebody please be kind enough to guide me through?

**Comment by pbnjay** [comment]
Hello, I think you should find some other tool without "poorly written software description" so that you can get the results you desire. You will certainly not get free help from anyone here with this tone.
