### ISSUE TITLE
Unable to find gene in UNIPORT

### ISSUE THREAD

**Issue by oalavijeh** [joiningdata/lollipops#53]
Firstly, many thanks for taking the time to develop this really useful tool! 

I am trying to run the following:

`./lollipops IFT140 [some variants] `

And getting:
```
GNC Symbol:  IFT140
Uniprot returned 8 hits for your gene symbol 'IFT140':
Entry	Entry name	Status	Gene names	Organism
Q9HBG6	IF122_HUMAN	reviewed	IFT122 SPG WDR10 WDR140	Homo sapiens (Human)
Q8NDW8	TT21A_HUMAN	reviewed	TTC21A STI2	Homo sapiens (Human)
Q7Z4L5	TT21B_HUMAN	reviewed	TTC21B IFT139 KIAA1992 Nbla10696	Homo sapiens (Human)
Q96FT9	IFT43_HUMAN	reviewed	IFT43 C14orf179	Homo sapiens (Human)
Q9P2L0	WDR35_HUMAN	reviewed	WDR35 IFT121 KIAA1336	Homo sapiens (Human)
Q8NEZ3	WDR19_HUMAN	reviewed	WDR19 IFT144 KIAA1638	Homo sapiens (Human)
Q96NG3	ODAD4_HUMAN	reviewed	ODAD4 TTC25	Homo sapiens (Human)
```

However, on the UNIPORT website: https://www.uniprot.org/uniprot/Q96RY7#sequences the gene seems to exist. 

I have tried importing my own json version of this gene and running locally: https://pfam.xfam.org/protein/Q96RY7/graphic

With this code:
`./lollipops -l="./ift140.json" -o="json.svg"  [some variants] `

As per a previous issue but I keep getting this:
```
HGNC Symbol:  Q383X
Uniprot returned 0 hits for your gene symbol 'Q383X':
Unable to find protein ID for 'Q383X' (use -U XX to select one of the above)
```

Q383X is the first variant I am hoping to plot....

Your advice would be much appreciated thanks

All the best

**Comment by pbnjay** [comment]
I believe the command you want (to search using Uniprot ID instead of Symbol) would be:

```./lollipops -U Q96RY7 Q383X```

Although even this may not help much, I don't see any annotated domains in pfam where the graphic data comes from. If you wanted to show everything you can try this:

```./lollipops -show-disordered -show-motifs -labels -U Q96RY7 Q383X```

![Screen Shot 2021-07-19 at 1 39 05 PM](https://user-images.githubusercontent.com/161552/126202992-b0846edd-905c-4d37-9262-2df6bbe800bc.png)

**Comment by oalavijeh** [comment]
Many thanks for taking the time to answer!
