### ISSUE TITLE
Uniprot ID of gene isoform

### ISSUE THREAD

**Issue by tea-egg-sheldon** [joiningdata/lollipops#62]
I was unable to create the lollipop chart by using the gene ID of a gene's isoform :
 ./lollipops -U Q8NB90-2 
pfam returned invalid result

**Comment by evcon131** [comment]
Same here but I get it with any uniprot ID, including ones that used to work

**Comment by sainadfensi** [comment]
I have encountered the same issue, worked before.

**Comment by lhelseth** [comment]
I'm experiencing the same issue using the latest patch ([lollipops-v1.5.4-linux64.tar.gz](https://github.com/joiningdata/lollipops/releases/download/v1.5.4/lollipops-v1.5.4-linux64.tar.gz) and any Uniprot ID.  The pfam site you link to is redirecting to a new site (retiring the legacy site Jan 2023) so I can't use the -l=filename.json option.  Any advice would be greatly appreciated.  Thanks.

**Comment by pbnjay** [comment]
This is now fixed in the latest release:
https://github.com/joiningdata/lollipops/releases/tag/v1.5.6
