### ISSUE TITLE
update Pfam links

### ISSUE THREAD

**Issue by typhainepl** [joiningdata/lollipops#63]
Hi,
The Pfam website has been decommissioned. It is accessible through https://pfam-legacy.xfam.org/ until early January 2023.
Pfam data are now accessible through the InterPro website (https://www.ebi.ac.uk/interpro) and API (https://www.ebi.ac.uk/interpro/api).

**Comment by pbnjay** [comment]
Thanks for the PR, merged and released here:
https://github.com/joiningdata/lollipops/releases/tag/v1.5.6
