### ISSUE TITLE
Examples fail, uniprot error: 400 Bad Request. Error in UniProt ID lookup?

### ISSUE THREAD

**Issue by jzinno** [joiningdata/lollipops#65]
When running the example `./lollipops TP53 R273C R175H T125 R248Q` the program returns `uniprot error: 400 Bad Request`.

Providing the UniProt ID directly however (`./lollipops -U P04637 R273C R175H T125 R248Q`) does work as expected.

**Comment by lhelseth** [comment]
I'm getting an error with the pfam-legacy site's certificate having expired today:
lollipops-v1.5.6-linux64/lollipops -f=/usr/share/fonts/liberation/LiberationSans-Regular.ttf -w=1400 -o=test.png -legend -labels -U O60216 R65*
Get "https://pfam-legacy.xfam.org/protein/O60216/graphic": x509: certificate has expired or is not yet valid: current time 2022-11-28T10:55:51-06:00 is after 2022-11-28T15:49:02Z

**Comment by tschmenger** [comment]
Additionally, when running the example with `./lollipops -uniprot -U P04637 R273C R175H T125 R248Q` to bypass pfam, as per documentation, the code runs but produces a basically empty .svg (only a grey horizontal bar is shown).

**Comment by JamesR-S** [comment]
As a stopgap you can modify the http.get command in http.go as follows and recompile the code:

`func httpGet(url string) (*http.Response, error) {
	tr := &http.Transport{
        TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
    }
    client := &http.Client{Transport: tr}
    return client.Get(url)
}`

This will ignore the certificate.

**Comment by JamesR-S** [comment]
Oh and you will also need to add `"crypto/tls"` to the imported libraries

**Comment by coolmak32** [comment]
Hi JamesR, 

Thank for the help. 
I am not a coder of having any such expertise. Can you please elaborate your solution in a more easy to follow steps. I know it may require your precious time but if you can help that'd be much appreciated. 

Thank you

**Comment by shehzad-99** [comment]
Hey coolmak32,
Download the source file from their version page. Then add the code into the http.go file that will be present in the data folder that you download. Don't forget to add the library that he mentioned in the import section as well. Once you have done that and saved the file you can go back to the main folder that you downloaded the file and run the command "go build".

**Comment by coolmak32** [comment]
> Hey coolmak32,
> Download the source file from their version page. Then add the code into the http.go file that will be present in the data folder that you download. Don't forget to add the library that he mentioned in the import section as well. Once you have done that and saved the file you can go back to the main folder that you downloaded the file and run the command "go build".

Hi shehzad, as per your suggestion, I modified the http.go file and ran the command "go build". But now I am getting this error; "uniprot error: 400 Bad Request". 

This is the modified http.go file of mine:

// +build !wasm

package data

import (
 	"net/http"
 	"net/url"
     "crypto/tls"
 )

 func httpGet(url string) (*http.Response, error) {
 	return http.Get(url)
 	tr := &http.Transport{
         TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
     }
     client := &http.Client{Transport: tr}
     return client.Get(url)
 }

 func httpPostForm(url string, vals url.Values) (*http.Response, error) {
	return http.PostForm(url, vals)
}


Am I missing something here?

Thanks for your time

**Comment by coolmak32** [comment]
(base) kuldeepmakwana@Kuldeeps-MacBook-Air lollipops1_5_6 %     ./lollipops -legend -labels TP53 R248Q#7f3333@131 R273C R175H T125@5
HGNC Symbol:  TP53
uniprot error: 400 Bad Request
(base) kuldeepmakwana@Kuldeeps-MacBook-Air lollipops1_5_6 %     ./lollipops -legend -labels -U Q12888 R248Q#7f3333@131 R273C R175H T125@5
Get "https://pfam-legacy.xfam.org/protein/Q12888/graphic": x509: “*.xfam.org” certificate is expired
(base) kuldeepmakwana@Kuldeeps-MacBook-Air lollipops1_5_6 %

**Comment by shehzad-99** [comment]
> > Hey coolmak32,
> > Download the source file from their version page. Then add the code into the http.go file that will be present in the data folder that you download. Don't forget to add the library that he mentioned in the import section as well. Once you have done that and saved the file you can go back to the main folder that you downloaded the file and run the command "go build".
> 
> Hi shehzad, as per your suggestion, I modified the http.go file and ran the command "go build". But now I am getting this error; "uniprot error: 400 Bad Request".
> 
> This is the modified http.go file of mine:
> 
> // +build !wasm
> 
> package data
> 
> import ( "net/http" "net/url" "crypto/tls" )
> 
> func httpGet(url string) (*http.Response, error) { return http.Get(url) tr := &http.Transport{ TLSClientConfig: &tls.Config{InsecureSkipVerify: true}, } client := &http.Client{Transport: tr} return client.Get(url) }
> 
> func httpPostForm(url string, vals url.Values) (*http.Response, error) { return http.PostForm(url, vals) }
> 
> Am I missing something here?
> 
> Thanks for your time

TP53 is not the uniprot id, run the example that’s provided in the first comment using the uniprot id

**Comment by shehzad-99** [comment]
If the certificate issue still persists, you’re probably not using the correct lollipops file you built, idk what else could be the problem

**Comment by coolmak32** [comment]
Hi!
Thanks, got it working. I was picking up wrong uniport ID.
I can print the plots now. 

Thanks a lot.

**Comment by pbnjay** [comment]
This should be resolved as of the [latest release](https://github.com/joiningdata/lollipops/releases/tag/v1.6.0), thanks for reporting and to JamesR-S for the fix
