### ISSUE TITLE
pfam certificate has expired or is not yet valid:

### ISSUE THREAD

**Issue by pradyumnasagar** [joiningdata/lollipops#67]
I got pfam certificate error please help
Get "https://pfam-legacy.xfam.org/protein/Q00937/graphic": x509: certificate has expired or is not yet valid: current time 2023-01-08T17:16:27+05:30 is after 2022-11-28T15:49:02Z
(R4)

**Comment by coolmak32** [comment]
Were you able to solve this?

**Comment by pradyumnasagar** [comment]
> Were you able to solve this?

Not exactly, got a workaround, use the link and save the graphic as a JSON file and use the JSON file as input worked.

**Comment by coolmak32** [comment]
can you please paste the link? I think you forget to copy it. 


Thank you

**Comment by pbnjay** [comment]
This should be resolved as of the [latest release](https://github.com/joiningdata/lollipops/releases/tag/v1.6.0), thanks for reporting and to JamesR-S for the fix
