### ISSUE TITLE
./main.go:218:8: undefined: createOutput

### ISSUE THREAD

**Issue by alig99** [joiningdata/lollipops#69]
Hi, 
I regularly use your fantastic lollipop plot software, but I am having issues with it recently, please can you help.

go run main.go -legend -labels -show-motifs THOC2 R77C#000000 L313F#000000

# command-line-arguments
./main.go:218:8: undefined: createOutput

Any help would be greatly appreciated,  thank you ali

**Comment by pbnjay** [comment]
you need the full binary, you can't run it with just `go run main.go` cause that doesn't include all the code files.
run `go build .` and then `./lollipops -legend ...` and it should work for you.
