### ISSUE TITLE
Pfam vs InterPro: TP53

### ISSUE THREAD

**Issue by ngs-seqer** [joiningdata/lollipops#73]
This is a separate issue. Since -pfam did not work for me, I tried

TP53's Pfam info hosted in InterPro 

https://www.ebi.ac.uk/interpro/protein/UniProt/P04637/entry/pfam/#table

UniProt domain version.

https://www.uniprot.org/uniprotkb/P04637/feature-viewer

Both have "P53, DNA-binding domain (100-288)", but this domain is missing when I generate a lollipop plot with

lollipops  -o=TP53.png  --labels  TP53  (without -pfam)

Any comments?

**Comment by pbnjay** [comment]
Please try again with the latest release!
