### ISSUE TITLE
can not find the output file

### ISSUE THREAD

**Issue by ArmStrogg** [joiningdata/lollipops#76]
Hi! I'm a beginner of your excellent tool. When I try to follow the example, I cannot find the output file in current path(where the .exe file located). How can I set the output path?
version: lollipops_1.7.1_windows_amd64

**Comment by pbnjay** [comment]
Hi, you can set the output path with -o but I can’t help much without know what you’re trying. I suggest trying the command line if you aren’t already as it will include more details
