### ISSUE TITLE
Website app appears to be broken?

### ISSUE THREAD

**Issue by eaferrante** [joiningdata/lollipops#81]
I am working with Lollipops to generate a lolliplot for NOTCH3 based on a patient cohort I have and after adding the variant information with the specified format to the application (https://joiningdata.com/lollipops/index.html), the wheel just sits there spinning for several hours. Is the application functional?

Thank you!

**Comment by matthiasblum** [comment]
The web version of `lollilop` (https://joiningdata.com/lollipops/index.html) is out-of-date. Please use the command line version.
