### ISSUE TITLE
InterPro Error:404 not Found 

### ISSUE THREAD

**Issue by siddhantattri** [joiningdata/lollipops#82]
Installed the lollipops_1.7.1_windows_amd64 and ran the following command according to the readme file :

lollipops.exe TP53 R273C R175H T125 R248Q

It fails with the following output:
HGNC Symbol:  TP53
Uniprot/SwissProt Accession:  P04637
InterPro error: 404 Not Found

**Comment by matthiasblum** [comment]
[Version 1.7.1](https://github.com/joiningdata/lollipops/releases/tag/v1.7.1) is slightly outdated. Please build the project from the source code.
